-- Options OI Snapshots table
-- Stores morning/evening snapshots for OI shift detection

CREATE TABLE IF NOT EXISTS options_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL DEFAULT 'NIFTY',
    run TEXT NOT NULL,  -- 'morning' or 'evening'
    date DATE NOT NULL,
    spot_price DOUBLE PRECISION,
    max_pain DOUBLE PRECISION,
    pcr DOUBLE PRECISION,
    pcr_signal TEXT,
    support_zone JSONB,  -- JSON array of strike prices
    resistance_zone JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_options_snapshots_date_run
ON options_snapshots (date DESC, run DESC);

CREATE INDEX IF NOT EXISTS idx_options_snapshots_symbol
ON options_snapshots (symbol, date DESC);

-- Enable RLS
ALTER TABLE options_snapshots ENABLE ROW LEVEL SECURITY;

-- Policy (allow all for now - can restrict later)
CREATE POLICY "Allow all for options_snapshots" ON options_snapshots
    FOR ALL USING (true);

-- Purge function: delete snapshots older than 7 days
CREATE OR REPLACE FUNCTION purge_old_options_snapshots()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM options_snapshots 
    WHERE created_at < NOW() - INTERVAL '7 days';
END;
$$;

-- Auto-purge: run before each insert (via trigger)
CREATE OR REPLACE FUNCTION auto_purge_options_snapshots()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM options_snapshots 
    WHERE created_at < NOW() - INTERVAL '7 days';
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-purge on insert
DROP TRIGGER IF EXISTS trigger_purge_options_snapshots ON options_snapshots;
CREATE TRIGGER trigger_purge_options_snapshots
BEFORE INSERT ON options_snapshots
FOR EACH ROW
EXECUTE FUNCTION auto_purge_options_snapshots();
